export const THEMES = {
  0: (panelTransparent: boolean) => ({
    name: 'Void',
    panel: {
      background: panelTransparent ? 'transparent' : '#0a0a0a',
      border: 'none',
      borderRadius: '0',
      boxShadow: 'none',
      backdropFilter: 'none'
    },
    header: {
      background: 'transparent',
      border: 'none',
      borderRadius: '0',
      color: '#ffffff',
      fontFamily: 'monospace',
      fontWeight: '400',
      letterSpacing: '0.5px',
      textShadow: 'none',
      boxShadow: 'none',
      padding: '8px 0',
      marginBottom: '8px'
    },
    button: (active: boolean, type?: string) => ({
      background: 'transparent',
      border: 'none',
      borderRadius: '0',
      color: active ? '#ffffff' : '#666666',
      fontFamily: 'monospace',
      textTransform: 'none' as const,
      letterSpacing: '0.3px',
      fontWeight: active ? '500' : '400',
      textShadow: 'none',
      boxShadow: 'none',
      textDecoration: active ? 'underline' : 'none',
      textUnderlineOffset: active ? '4px' : '0',
      padding: '4px 8px',
      minHeight: 'auto',
      lineHeight: '1.2'
    }),
    clear: {
      background: 'transparent',
      color: '#ff6b6b',
      border: 'none',
      borderRadius: '0',
      fontFamily: 'monospace',
      textTransform: 'none',
      fontWeight: '400',
      textShadow: 'none',
      boxShadow: 'none',
      padding: '4px 8px',
      minHeight: 'auto',
      lineHeight: '1.2'
    },
    autoButton: (active: boolean, enabled: boolean) => ({
      background: 'transparent',
      border: 'none',
      borderRadius: '0',
      color: enabled ? (active ? '#ffffff' : '#666666') : '#333333',
      fontFamily: 'monospace',
      fontWeight: active ? '500' : '400',
      opacity: 1,
      cursor: enabled ? 'pointer' : 'not-allowed',
      textShadow: 'none',
      boxShadow: 'none',
      outline: 'none',
      textDecoration: active ? 'underline' : 'none',
      textUnderlineOffset: active ? '4px' : '0',
      padding: '4px 8px',
      minHeight: 'auto',
      lineHeight: '1.2'
    }),
    optionButton: (active: boolean) => ({
      background: 'transparent',
      border: 'none',
      borderRadius: '0',
      color: active ? '#ffffff' : '#666666',
      fontFamily: 'monospace',
      fontWeight: active ? '500' : '400',
      textTransform: 'none' as const,
      letterSpacing: '0.3px',
      textShadow: 'none',
      boxShadow: 'none',
      textDecoration: active ? 'underline' : 'none',
      textUnderlineOffset: active ? '4px' : '0',
      padding: '4px 8px',
      minHeight: 'auto',
      lineHeight: '1.2'
    })
  }),
};
